### ISSUE TITLE
Copy formulas in Google spreadsheet

### ISSUE THREAD

**Issue by heatherleaf** [ChalmersGU-data-structure-courses/lab-system#40]
Formulas in the template tab are copied when a new row is created in a lab tab.

E.g. in the current LP2 instance we have a formula in column B which is not copied when a new person/group joins so I have to copy it manually 

Related (but even more difficult to implement I guess): conditional formating rules are not copied when a new lab tab is created

**Comment by heatherleaf** [comment]
> And now the workaround: all cells with formulas referencing the group row range compute the range in a way that does not reference the group range itself. For example with five header rows:
> 
>     =COUNTA(INDIRECT("B"&ROWS(1:5)+1&":B"),0)
> 
> Updating the group row range does not disturb the computed range. Adding header rows updates it as desired, except for the case that the header row is added after row 5. Then we are back to an instance of the previous problem. But the template is not updated often, so we can deal with this.

The problem with this is that if we want to copy the formula to another column (e.g. for Query#2), then it will still refer to column B. Another problem

Here's an option that's "copy-safe": `COUNTA(B5:B)-1`. 
Simply include the header (B5), but deduce 1 from the count. 
If you want to sum a column it's simply `SUM(B5:B)`, provided that the header B5 is non-numeric.

And a really complex copy-safe option: 
`=COUNTA(INDIRECT(ADDRESS(6,COLUMN()-2)&":"&ADDRESS(9999,COLUMN()-2)))`.
But this does not update if we add/remove header rows.

**Comment by sattlerc** [comment]
> The problem with this is that if we want to copy the formula to another column (e.g. for Query#2), then it will still refer to column B.

You are right.

> Here's an option that's "copy-safe": `COUNTA(B5:B)-1`. Simply include the header (B5), but deduce 1 from the count. If you want to sum a column it's simply `SUM(B5:B)`, provided that the header B5 is non-numeric.
>
> And a really complex copy-safe option: `=COUNTA(INDIRECT(ADDRESS(6,COLUMN()-2)&":"&ADDRESS(9999,COLUMN()-2)))`. But this does not update if we add/remove header rows.

I think we can make the range copy/insert-safe and not dependent on assumptions about the header row as follows:

```basic
INDIRECT("R" & ROWS(1:5) + 1 & "C" & COLUMN() & ":" & "C" & COLUMN() + 1, FALSE)
```

**Comment by heatherleaf** [comment]
> `INDIRECT("R" & ROWS(1:5) + 1 & "C" & COLUMN() & ":" & "C" & COLUMN(), FALSE)`

`LET(r, "R" & ROWS(1:5)+1, LET(c, "C" & COLUMN(), INDIRECT(r & c & ":" & c, FALSE)))`

**Comment by sattlerc** [comment]
Top statistics:

```basic
LET(c, "C" & COLUMN(), INDIRECT("R" & ROW(A5) + 1 & c & ":" & c, FALSE))
```

Bottom statistics:

```basic
LET(c, "C" & COLUMN(), INDIRECT("R" & ROW(A1) + 1 & c & ":R" & ROW(A6) - ROWS(3:6) & c, FALSE))
```

**Comment by sattlerc** [comment]
I've updated the template document.
