### ISSUE TITLE
Several submission tags pointing to the same commit

### ISSUE THREAD

**Issue by heatherleaf** [ChalmersGU-data-structure-courses/lab-system#56]
If you have several submission tags for the same commit the lab system can behave a little strange:

https://git.chalmers.se/courses/data-structures/lp2/2024/lab-2/lab2-group-46/-/merge_requests/1

- they made two submission tags on the same commit (27 Nov)
- Naïm graded it (29 Nov) and marked as incomplete
- the system changed back to waiting-for-grading (5 Dec), without any new commits or anything
- (then I changed back to incomplete, but that's irrelevant to this issue)

It seems like the system doesn't realise that the two tags point to the same commit.

**Comment by sattlerc** [comment]
The lab system only synchronizes the latest submission tag, but probably does not have a check for equal submission tags. Maybe the comparison of submission tags for the same commit is unstable? Originally, it decided that `submission2 < submission1`. Maybe it got restarted and then decided that `submission2 < submission1`?

**Comment by heatherleaf** [comment]
So perhaps just compare

    (date1,name1) < (date2,name2)

Instead of `date1 < date2`
